#!/usr/bin/env bash
set -e
mount /dev/sda1
zcat /proc/config.gz > /usr/src/linux/.config
cd /usr/src/linux
make oldconfig
#make menuconfig
make -j5
make modules_install
emerge @module-rebuild
cp arch/x86/boot/bzImage /boot/EFI/Gentoo/bzImage.efi
cd /etc/efikeys/
sbsign --key db.key --cert db.crt --output /boot/EFI/Gentoo/bzImage.efi /boot/EFI/Gentoo/bzImage.efi
